// Centralized product data from Google Sheet — all Amazon affiliate links

export interface Product {
  name: string;
  amazonName: string;
  url: string;
  category: string;
  price?: string;
  priceNote?: string;
  rating?: string;
  ratingCount?: string;
  badge?: string;
  badgeColor?: 'default' | 'destructive' | 'outline' | 'secondary';
  recommended?: boolean;
  pros: string[];
  cons: string[];
  bestFor: string;
  preSaleText?: string;
  ctaLabel?: string;
}

// ═══════════════════════════════════════════
//  SACS À DOS
// ═══════════════════════════════════════════
export const SACS_A_DOS: Product[] = [
  {
    name: "Cabin Max 40L – Format cabine garanti ✈️",
    amazonName: "Cabin Max Bagage Cabine 55x40x20",
    url: "https://amzn.to/3NDamaO",
    category: "sac-a-dos",
    price: "~50€",
    priceNote: "Petit budget",
    rating: "4.4/5",
    ratingCount: "1 500+ avis",
    badge: "💰 Petit budget",
    badgeColor: "secondary",
    pros: ["Compatible Ryanair / EasyJet / Vueling", "Ultra-léger et prix imbattable", "Ouverture frontale type valise"],
    cons: ["Confort de portage basique", "Pas de ceinture ventrale"],
    bestFor: "Voyageurs occasionnels ou budget serré qui veulent un sac cabine simple et efficace",
    preSaleText: "👉 Idéal pour voyager léger sans payer de bagage en soute.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Osprey Farpoint 50L – La référence backpacking 🌍",
    amazonName: "Osprey Farpoint Homme Sac de voyage",
    url: "https://amzn.to/4sNnPvQ",
    category: "sac-a-dos",
    price: "~150€",
    priceNote: "Référence voyage",
    rating: "4.8/5",
    ratingCount: "3 000+ avis",
    badge: "🏆 Notre recommandation",
    recommended: true,
    pros: ["Confort exceptionnel — ceinture ventrale rembourrée", "Ouverture valise, bretelles escamotables", "50L parfait pour 2+ semaines de voyage"],
    cons: ["Ne passe pas en cabine low-cost", "Plus lourd qu'un 40L (~1,8 kg)"],
    bestFor: "La référence pour le backpacking et les voyages itinérants de longue durée",
    preSaleText: "👉 Idéal pour les voyageurs sérieux qui veulent le meilleur confort de portage.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Cabin Max Metz 30L – Ultra-compact week-end 🧳",
    amazonName: "Cabin Max Metz 30L",
    url: "https://amzn.to/4rI55gf",
    category: "sac-a-dos",
    price: "~35€",
    priceNote: "Format week-end",
    rating: "4.3/5",
    ratingCount: "800+ avis",
    badge: "🧳 Compact",
    badgeColor: "outline",
    pros: ["Format compact idéal pour city-trip", "Passe en bagage sous le siège (low-cost)", "Prix mini"],
    cons: ["Trop petit pour +3 jours", "Rembourrage dorsal minimal"],
    bestFor: "City-trips, week-ends prolongés et voyageurs ultra-minimalistes",
    preSaleText: "👉 Idéal pour les escapades courtes sans superflu.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
];

// ═══════════════════════════════════════════
//  VALISES CABINE
// ═══════════════════════════════════════════
export const VALISES_CABINE: Product[] = [
  {
    name: "Samsonite S'Cure – Résistance maximale ⭐",
    amazonName: "Samsonite S'Cure - Spinner S",
    url: "https://amzn.to/4smVigQ",
    category: "valise",
    price: "~120€",
    priceNote: "Qualité Samsonite",
    rating: "4.7/5",
    ratingCount: "5 000+ avis",
    badge: "🏆 Notre recommandation",
    recommended: true,
    pros: ["Polypropylène ultra-résistant aux chocs", "Fermeture 3 points sécurisée (pas de zip)", "4 roues doubles silencieuses, 34L"],
    cons: ["Un peu plus lourde (2,9 kg)", "Pas de serrure TSA intégrée"],
    bestFor: "Voyageurs qui veulent une valise solide et sécurisée pour des années",
    preSaleText: "👉 Idéal pour ceux qui veulent investir une seule fois dans une valise fiable.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "American Tourister Soundbox – Extensible et fun 🔥",
    amazonName: "American Tourister Soundbox",
    url: "https://amzn.to/4uBL6m4",
    category: "valise",
    price: "~90€",
    priceNote: "Excellent rapport qualité-prix",
    rating: "4.5/5",
    ratingCount: "10 000+ avis",
    badge: "💰 Meilleur rapport qualité-prix",
    badgeColor: "outline",
    pros: ["Extensible (+3,5 cm de profondeur)", "Large choix de coloris tendance", "Serrure TSA intégrée, 4 roues"],
    cons: ["Souple = moins de protection", "Fermeture éclair classique"],
    bestFor: "Voyageurs qui veulent flexibilité et style à petit prix",
    preSaleText: "👉 Idéal pour voyager en couleur sans exploser le budget.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
];

// ═══════════════════════════════════════════
//  ÉQUIPEMENT TECH
// ═══════════════════════════════════════════
export const EQUIPEMENT_TECH: Product[] = [
  {
    name: "Canon PowerShot SX740 HS – Zoom 40x de poche 📸",
    amazonName: "Canon PowerShot SX740 HS",
    url: "https://amzn.to/4dxjatr",
    category: "tech",
    price: "~400€",
    priceNote: "Compact expert",
    rating: "4.5/5",
    ratingCount: "2 500+ avis",
    badge: "🏆 Notre recommandation",
    recommended: true,
    pros: ["Zoom optique 40x — de 24 à 960mm", "Vidéo 4K, stabilisation optique", "Ultra-compact : tient dans une poche"],
    cons: ["Pas de viseur électronique", "Capteur limité en basse lumière"],
    bestFor: "Voyageurs qui veulent un zoom puissant dans un boîtier de poche",
    preSaleText: "👉 Idéal pour capturer les détails lointains sans trimballer un reflex.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "GoPro HERO12 Black – L'aventure en 5.3K 🔥",
    amazonName: "GoPro HERO12 Black",
    url: "https://amzn.to/4lEzESt",
    category: "tech",
    price: "~350€",
    priceNote: "Action cam référence",
    rating: "4.6/5",
    ratingCount: "4 000+ avis",
    badge: "🔥 Best seller",
    badgeColor: "outline",
    pros: ["Vidéo 5.3K, stabilisation HyperSmooth 6.0", "Étanche 10m sans caisson", "HDR, ralenti, timelapses intégrés"],
    cons: ["Pas idéal pour la photo pure", "Autonomie ~1h30 en 4K"],
    bestFor: "Sports, plongée, trek — tout ce qui bouge et éclabousse",
    preSaleText: "👉 Idéal pour les aventuriers qui veulent des vidéos spectaculaires.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "JOBY GorillaPod 1K Kit – Le trépied couteau-suisse 🧳",
    amazonName: "JOBY GorillaPod 1K Kit",
    url: "https://amzn.to/3Py5dS5",
    category: "tech",
    price: "~30€",
    priceNote: "Accessoire indispensable",
    rating: "4.5/5",
    ratingCount: "6 000+ avis",
    badge: "💰 Petit budget",
    badgeColor: "secondary",
    pros: ["S'accroche partout (branche, rampe…)", "Compatible smartphone + compact + GoPro", "Ultra-léger (170g) et compact"],
    cons: ["Pas pour les gros appareils (>1 kg)", "Stabilité limitée sur surface lisse"],
    bestFor: "Photos de groupe, timelapses et selfies en voyage",
    preSaleText: "👉 Idéal pour les voyageurs solo qui veulent des photos de groupe réussies.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "TESSAN Adaptateur Universel USB-C – 200+ pays 🌍",
    amazonName: "TESSAN Adaptateur Prise Universelle",
    url: "https://amzn.to/47GsXJW",
    category: "tech",
    price: "~20€",
    priceNote: "Essentiel",
    rating: "4.6/5",
    ratingCount: "8 000+ avis",
    badge: "⭐ Meilleur choix",
    badgeColor: "secondary",
    pros: ["Compatible 200+ pays (US, UK, EU, AU)", "3 USB-A + 1 USB-C intégrés", "Compact — remplace tous vos adaptateurs"],
    cons: ["Pas de convertisseur de tension", "Un peu encombrant avec les 4 fiches"],
    bestFor: "Tout voyageur international — l'accessoire à ne jamais oublier",
    preSaleText: "👉 Idéal pour ne plus jamais chercher le bon adaptateur à l'aéroport.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "UGREEN Zapix 20000mAh – Charge rapide 22.5W ⚡",
    amazonName: "UGREEN Zapix 22.5W Batterie Externe",
    url: "https://amzn.to/4seOOR0",
    category: "tech",
    price: "~30€",
    priceNote: "20000mAh",
    rating: "4.6/5",
    ratingCount: "3 500+ avis",
    badge: "🔥 Best seller",
    badgeColor: "outline",
    pros: ["20000 mAh — recharge un iPhone 4-5 fois", "Charge rapide 22.5W (USB-C + USB-A)", "Affichage LED du niveau de charge"],
    cons: ["Pèse ~350g", "Charge complète en ~6h"],
    bestFor: "Longues journées sans prise — trek, transports, festivals",
    preSaleText: "👉 Idéal pour ne jamais tomber en panne de batterie en voyage.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
];

// ═══════════════════════════════════════════
//  ACCESSOIRES DE VOYAGE
// ═══════════════════════════════════════════
export const ACCESSOIRES_VOYAGE: Product[] = [
  {
    name: "FLOWZOOM Dream Coussin – Mousse mémoire premium 😴",
    amazonName: "FLOWZOOM Dream Coussin de Voyage",
    url: "https://amzn.to/3PLtEeO",
    category: "accessoire",
    price: "~35€",
    priceNote: "Confort premium",
    rating: "4.5/5",
    ratingCount: "1 200+ avis",
    badge: "🏆 Notre recommandation",
    recommended: true,
    pros: ["Mousse à mémoire de forme ultra-confort", "Housse lavable, compressible dans sa pochette", "Maintien cervical excellent pour l'avion"],
    cons: ["Plus volumineux qu'un gonflable", "Prix un peu élevé pour un coussin"],
    bestFor: "Vols long-courriers et bus de nuit — pour dormir (vraiment) en voyage",
    preSaleText: "👉 Idéal pour ceux qui veulent enfin dormir confortablement en avion.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Maliton Trousse Suspendue – Organisation parfaite 🧳",
    amazonName: "Maliton Trousse de Toilette",
    url: "https://amzn.to/4uBUuGk",
    category: "accessoire",
    price: "~15€",
    priceNote: "Très bon rapport qualité-prix",
    rating: "4.4/5",
    ratingCount: "2 000+ avis",
    badge: "🔥 Best seller",
    badgeColor: "outline",
    pros: ["Se suspend au crochet — gain de place énorme", "Compartiments multiples, poche TSA", "Imperméable et facile à nettoyer"],
    cons: ["Peut être grande pour les minimalistes", "Crochet un peu fragile"],
    bestFor: "Organisation parfaite de vos affaires de toilette en voyage",
    preSaleText: "👉 Idéal pour les voyageurs qui veulent tout retrouver en un instant.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Eono Serviette Microfibre – Sèche 3x plus vite 💨",
    amazonName: "Eono Serviette en Microfibre",
    url: "https://amzn.to/4bT0VNR",
    category: "accessoire",
    price: "~12€",
    priceNote: "Indispensable",
    rating: "4.5/5",
    ratingCount: "5 000+ avis",
    badge: "⭐ Meilleur choix",
    badgeColor: "secondary",
    pros: ["Sèche 3x plus vite qu'une serviette classique", "Ultra-compacte dans sa pochette", "Antibactérienne — plage et rando"],
    cons: ["Toucher différent du coton", "Grandes tailles un peu encombrantes"],
    bestFor: "Backpackers, plage, piscine — tout voyageur qui veut gagner de la place",
    preSaleText: "👉 Idéal pour voyager léger sans sacrifier le confort après la douche.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Cadenas TSA Lot de 2 – Sécurité partout 🔒",
    amazonName: "Cadenas TSA 2 Pièce",
    url: "https://amzn.to/4uF3LgM",
    category: "accessoire",
    price: "~10€",
    priceNote: "Lot de 2",
    rating: "4.3/5",
    ratingCount: "3 000+ avis",
    badge: "💰 Petit budget",
    badgeColor: "secondary",
    pros: ["Approuvé TSA — les agents ouvrent sans forcer", "Combinaison 3 chiffres, pas de clé à perdre", "Lot de 2 : sac + casier"],
    cons: ["Petit format — pas pour toutes les fermetures", "Combinaison 3 chiffres seulement"],
    bestFor: "Sécuriser sac, valise et casiers d'auberge — indispensable partout",
    preSaleText: "👉 Idéal pour sécuriser ses affaires en auberge de jeunesse.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Alpine SleepDeep – Silence garanti en dortoir 😴",
    amazonName: "Alpine SleepDeep Bouchons d'Oreilles",
    url: "https://amzn.to/4s0QiO5",
    category: "accessoire",
    price: "~20€",
    priceNote: "Qualité premium",
    rating: "4.4/5",
    ratingCount: "1 500+ avis",
    badge: "✈️ Idéal cabine",
    badgeColor: "outline",
    pros: ["Réduction sonore optimale — filtres acoustiques", "Confortables même pour dormir sur le côté", "Réutilisables et hypoallergéniques"],
    cons: ["Prix plus élevé que les jetables", "Taille unique"],
    bestFor: "Dortoirs d'auberge, avions et hôtels bruyants — sommeil garanti",
    preSaleText: "👉 Idéal pour enfin dormir en dortoir sans être réveillé à 3h du matin.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
];

// ═══════════════════════════════════════════
//  VÊTEMENTS VOYAGE
// ═══════════════════════════════════════════
export const VETEMENTS_VOYAGE: Product[] = [
  {
    name: "SAGUARO Minimalistes – La chaussure couteau-suisse 🥾",
    amazonName: "SAGUARO Unisexe Chaussures Minimaliste",
    url: "https://amzn.to/4lF5XAY",
    category: "vetement",
    price: "~35€",
    priceNote: "Ultra-polyvalentes",
    rating: "4.4/5",
    ratingCount: "8 000+ avis",
    badge: "🏆 Notre recommandation",
    recommended: true,
    pros: ["Ultra-légères et pliables dans le sac", "Semelle grip, adhérence trail correcte", "Respirantes, sèchent vite après la pluie"],
    cons: ["Protection limitée sur terrain rocheux", "Style minimaliste pas au goût de tous"],
    bestFor: "Rando légère, ville et plage — la chaussure couteau-suisse du voyageur",
    preSaleText: "👉 Idéal pour voyager avec une seule paire de chaussures polyvalente.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "FLARUT Sandales de Marche – Confort tropiques 🏖️",
    amazonName: "FLARUT Sandales de Marche",
    url: "https://amzn.to/4bRPaaI",
    category: "vetement",
    price: "~30€",
    priceNote: "Confort marche",
    rating: "4.3/5",
    ratingCount: "2 000+ avis",
    badge: "💰 Petit budget",
    badgeColor: "secondary",
    pros: ["Semelle épaisse et amortie pour marcher longtemps", "Séchage rapide, parfaites pour la plage", "Sangles ajustables, bon maintien du pied"],
    cons: ["Un peu volumineuses dans le sac", "Style sportif uniquement"],
    bestFor: "Asie du Sud-Est, plages et marche en ville par temps chaud",
    preSaleText: "👉 Idéal pour explorer les temples et les plages sans souffrir des pieds.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Merino.tech T-shirt Mérinos – 3 jours sans odeurs 🐑",
    amazonName: "Merino.tech Tee Shirt",
    url: "https://amzn.to/4uDAvXN",
    category: "vetement",
    price: "~45€",
    priceNote: "Investissement durable",
    rating: "4.5/5",
    ratingCount: "1 800+ avis",
    badge: "🔥 Best seller",
    badgeColor: "outline",
    pros: ["Laine mérinos : anti-odeurs, thermorégulante", "Portez-le 3-4 jours sans le laver !", "Doux et léger — ne gratte pas du tout"],
    cons: ["Prix élevé vs coton classique", "Fragile au lavage machine"],
    bestFor: "Backpackers et voyageurs minimalistes — moins de linge = moins de poids",
    preSaleText: "👉 Idéal pour réduire son bagage de moitié grâce au mérinos.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "Columbia Watertight II – Imperméable compressible 🌧️",
    amazonName: "Columbia Veste Watertight II",
    url: "https://amzn.to/4sU7xkI",
    category: "vetement",
    price: "~60€",
    priceNote: "Imperméable légère",
    rating: "4.5/5",
    ratingCount: "4 000+ avis",
    badge: "⭐ Meilleur choix",
    badgeColor: "outline",
    pros: ["Imperméable et coupe-vent Omni-Tech", "Se compresse dans sa propre poche", "Légère (~250g), coutures étanches"],
    cons: ["Pas de doublure chaude", "Taille US — prendre une taille en dessous"],
    bestFor: "Pluie soudaine, vent en montagne, soirées fraîches — toujours dans le sac",
    preSaleText: "👉 Idéal pour ne plus jamais être pris au dépourvu par la pluie.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
  {
    name: "JustSun Short 2-en-1 – Plage et ville 🏖️",
    amazonName: "JustSun Short de Bain",
    url: "https://amzn.to/4lEcADm",
    category: "vetement",
    price: "~20€",
    priceNote: "Multi-usage",
    rating: "4.3/5",
    ratingCount: "6 000+ avis",
    badge: "💰 Petit budget",
    badgeColor: "secondary",
    pros: ["Short de bain + short de ville = 2 en 1", "Séchage ultra-rapide, poches zippées", "Look sobre qui passe partout"],
    cons: ["Tissu fin — pas pour la randonnée", "Cordon de serrage basique"],
    bestFor: "Plage, piscine et balade en ville — l'indispensable des pays chauds",
    preSaleText: "👉 Idéal pour les pays chauds sans multiplier les shorts dans le sac.",
    ctaLabel: "👉 Voir le prix et les avis sur Amazon",
  },
];
