import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Shield } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const AssuranceVoyageJapon = () => {
  const faqs = [
    { question: "L'assurance voyage est-elle obligatoire pour le Japon ?", answer: "Non, elle n'est pas obligatoire mais fortement recommandée. Les frais médicaux au Japon sont très élevés (une hospitalisation peut coûter 3 000-10 000€)." },
    { question: "Quelle assurance choisir pour le Japon ?", answer: "Chapka Cap Aventure (dès 32€/mois) et Heymondo (dès 37€/semaine) sont nos recommandations. Les deux couvrent les frais médicaux, le rapatriement et les bagages." },
    { question: "La carte bancaire suffit-elle ?", answer: "Les cartes Visa Premier/Gold offrent une assurance basique (90 jours max) mais avec des plafonds souvent insuffisants et des exclusions. Une assurance dédiée est plus sûre." },
  ];
  return (
    <div className="min-h-screen flex flex-col">
      <SEO title="Assurance Voyage Japon : Laquelle Choisir ?" description="Guide assurance voyage pour le Japon. Comparatif Chapka, Heymondo, carte bancaire : couvertures, prix et conseils pour bien s'assurer au Japon." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-06-29" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Assurance Japon", url: "/blog/assurance-voyage-japon" }]} />
      <Header />
      <main className="flex-grow pt-24">
        <header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Guide Pratique</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Assurance Voyage Japon : Laquelle Choisir ?</h1><p className="text-xl text-white/90">Comparatif et conseils pour bien s'assurer au Japon</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 29 juin 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 8 min de lecture</span></div></div></div></header>
        <article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg">
          <p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">Le Japon est l'un des <strong>pays les plus sûrs du monde</strong>, mais les frais médicaux y sont <strong>très élevés</strong>. Une simple consultation coûte 50-100€, une hospitalisation peut grimper à plusieurs milliers d'euros. Une <strong>assurance voyage adaptée</strong> est donc indispensable pour partir l'esprit tranquille.</p>
          <h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Shield className="h-7 w-7 text-ocean" /> Pourquoi S'assurer ?</h2>
          <ul><li><strong>Frais médicaux</strong> : consultation 50-100€, hospitalisation 1 000-10 000€/jour</li><li><strong>Rapatriement</strong> : un rapatriement médical depuis le Japon coûte 15 000-50 000€</li><li><strong>Annulation</strong> : vol + hôtels + JR Pass = investissement significatif</li><li><strong>Bagages</strong> : perte ou vol (même rare au Japon, les transits peuvent poser problème)</li><li><strong>Catastrophes naturelles</strong> : tremblements de terre et typhons sont des risques réels</li></ul>
          <h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Shield className="h-7 w-7 text-ocean" /> Comparatif des Meilleures Assurances</h2>
          <div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 font-bold">Assurance</th><th className="py-3 px-4 font-bold">Prix</th><th className="py-3 px-4 font-bold">Frais médicaux</th><th className="py-3 px-4 font-bold">Points forts</th></tr></thead><tbody>
            <tr className="border-b border-border/50"><td className="py-2 px-4">Chapka Cap Aventure</td><td className="py-2 px-4">Dès 32€/mois</td><td className="py-2 px-4">200 000€</td><td className="py-2 px-4">Excellent rapport qualité-prix, sports couverts</td></tr>
            <tr className="border-b border-border/50"><td className="py-2 px-4">Heymondo</td><td className="py-2 px-4">Dès 37€/semaine</td><td className="py-2 px-4">500 000€</td><td className="py-2 px-4">Plafond élevé, app mobile pratique</td></tr>
            <tr className="border-b border-border/50"><td className="py-2 px-4">ACS Globe Partner</td><td className="py-2 px-4">Dès 29€/mois</td><td className="py-2 px-4">100 000€</td><td className="py-2 px-4">Budget, bonne couverture de base</td></tr>
            <tr className="border-b border-border/50"><td className="py-2 px-4">Carte Visa Premier</td><td className="py-2 px-4">Incluse</td><td className="py-2 px-4">11 000€</td><td className="py-2 px-4">Gratuite, mais plafond bas, 90 jours max</td></tr>
          </tbody></table></div>
          <h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Shield className="h-7 w-7 text-ocean" /> Que Couvrir en Priorité</h2>
          <ul><li><strong>Frais médicaux et hospitalisation</strong> : minimum 150 000€ de couverture</li><li><strong>Rapatriement</strong> : frais réels (pas de plafond)</li><li><strong>Responsabilité civile</strong> : en cas de dommage à un tiers</li><li><strong>Annulation/interruption</strong> : remboursement des frais prépayés</li><li><strong>Bagages</strong> : perte, vol ou retard</li></ul>
          <div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Notre recommandation : <strong>Chapka Cap Aventure</strong> pour le meilleur rapport qualité-prix, ou <strong>Heymondo</strong> pour un plafond médical plus élevé. Ne partez jamais sans assurance, même dans un pays aussi sûr que le Japon.</p></div>
          <FAQSection faqs={faqs} className="mt-10" />
          <OrganiserVoyageBlock destination="Japon" showAssurance showVols showHotel />
          <div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }, { label: "Budget voyage Japon", url: "/blog/budget-voyage-japon" }, { label: "Internet et eSIM au Japon", url: "/blog/internet-esim-japon" }].map((link, idx) => (<Link key={idx} to={link.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{link.label}</span></Link>))}</div></div>
          <div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
          <div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div>
        </article>
      </main>
      <Footer />
    </div>
  );
};
export default AssuranceVoyageJapon;
