import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Train } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const BudgetTransportJapon = () => { const faqs = [{ question: "Combien coûte le transport au Japon ?", answer: "Comptez 15-40€/jour selon l'intensité des déplacements. Le JR Pass (230-645€ pour 7-21 jours) peut considérablement réduire ce budget." }]; return (<div className="min-h-screen flex flex-col"><SEO title="Budget Transport Japon : Prix et Astuces" description="Budget transport détaillé au Japon. Prix du Shinkansen, métro, bus, taxi, JR Pass : combien coûtent les déplacements au Japon et comment économiser." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-14" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Budget Transport", url: "/blog/budget-transport-japon" }]} /><Header /><main className="flex-grow pt-24"><header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Budget</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Budget Transport au Japon : Tous les Prix</h1><p className="text-xl text-white/90">Shinkansen, métro, bus : combien coûtent les transports</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 14 juil. 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 10 min</span></div></div></div></header>
<article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg"><p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">Le transport est le <strong>poste le plus variable</strong> du budget au Japon. Un trajet en Shinkansen peut coûter 90€, mais un bus longue distance fait le même parcours pour 20€. Ce guide détaille <strong>tous les prix</strong> pour optimiser votre budget transport.</p>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Train className="h-7 w-7 text-ocean" /> Prix des Trajets Principaux</h2>
<div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 font-bold">Trajet</th><th className="py-3 px-4 font-bold">Shinkansen</th><th className="py-3 px-4 font-bold">Bus</th><th className="py-3 px-4 font-bold">Vol</th></tr></thead><tbody>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo → Kyoto</td><td className="py-2 px-4">14 170¥ (91€)</td><td className="py-2 px-4">3 000-5 000¥</td><td className="py-2 px-4">—</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo → Osaka</td><td className="py-2 px-4">14 520¥ (93€)</td><td className="py-2 px-4">3 000-5 000¥</td><td className="py-2 px-4">5 000-15 000¥</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo → Hiroshima</td><td className="py-2 px-4">19 080¥ (123€)</td><td className="py-2 px-4">5 000-8 000¥</td><td className="py-2 px-4">7 000-20 000¥</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo → Sapporo</td><td className="py-2 px-4">27 000¥ (174€)</td><td className="py-2 px-4">—</td><td className="py-2 px-4">5 000-20 000¥</td></tr>
</tbody></table></div>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Train className="h-7 w-7 text-ocean" /> Transport Urbain</h2>
<div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 font-bold">Transport</th><th className="py-3 px-4 font-bold">Prix</th></tr></thead><tbody>
<tr className="border-b border-border/50"><td className="py-2 px-4">Métro Tokyo (trajet)</td><td className="py-2 px-4">170-320¥ (1-2€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo Metro 24h</td><td className="py-2 px-4">600¥ (3,90€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo Metro 72h</td><td className="py-2 px-4">1 500¥ (9,70€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Bus Kyoto (trajet)</td><td className="py-2 px-4">230¥ (1,50€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Bus Kyoto pass 1 jour</td><td className="py-2 px-4">700¥ (4,50€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Taxi (prise en charge)</td><td className="py-2 px-4">730¥ (4,70€)</td></tr>
</tbody></table></div>
<div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Le transport au Japon est un <strong>investissement dans l'efficacité</strong>. Le Shinkansen est cher mais vous fait gagner des heures. Le bus de nuit est lent mais économise une nuit d'hôtel. Choisissez en fonction de votre priorité : temps ou argent.</p></div>
<FAQSection faqs={faqs} className="mt-10" /><OrganiserVoyageBlock destination="Japon" showVols showHotel />
<div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "JR Pass : faut-il l'acheter ?", url: "/blog/jr-pass-japon" }, { label: "Comment se déplacer", url: "/blog/comment-se-deplacer-japon" }, { label: "Budget voyage Japon", url: "/blog/budget-voyage-japon" }].map((l, i) => (<Link key={i} to={l.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{l.label}</span></Link>))}</div></div>
<div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
<div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div></article></main><Footer /></div>); };
export default BudgetTransportJapon;
