import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Camera } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const ChateauxJapon = () => {
  const faqs = [{ question: "Combien de châteaux originaux restent au Japon ?", answer: "Seulement 12 châteaux conservent leur donjon d'origine (avant les guerres et incendies). Himeji, Matsumoto, Hikone et Inuyama sont les plus impressionnants." }, { question: "Quel est le plus beau château du Japon ?", answer: "Himeji-jo est unanimement considéré comme le plus beau : UNESCO, 83 bâtiments, surnommé le 'héron blanc' pour sa blancheur éclatante." }];
  return (
    <div className="min-h-screen flex flex-col">
      <SEO title="Les Plus Beaux Châteaux Japonais : Top 10" description="Découvrez les 10 plus beaux châteaux du Japon. Himeji, Matsumoto, Osaka, Kumamoto : histoire, architecture et conseils pour visiter les châteaux japonais." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-04" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Châteaux Japon", url: "/blog/chateaux-japon" }]} />
      <Header />
      <main className="flex-grow pt-24">
        <header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Inspiration</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Les Plus Beaux Châteaux Japonais</h1><p className="text-xl text-white/90">10 forteresses féodales à visiter absolument</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 4 juillet 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 11 min de lecture</span></div></div></div></header>
        <article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg">
          <p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">Les châteaux japonais (<strong>shiro</strong>) sont des chefs-d'œuvre d'architecture militaire et esthétique. Construits entre le XIVe et le XVIIe siècle, ces forteresses aux <strong>toits élégants et murs de pierre imposants</strong> témoignent de l'ère des samouraïs. Sur les 5 000 châteaux originaux, seuls 12 conservent leur donjon d'époque.</p>
          <h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Camera className="h-7 w-7 text-ocean" /> Top 10 des Châteaux</h2>
          <h3 className="text-xl font-bold mt-6">1. Himeji-jo ⭐ – Le Héron Blanc</h3><p>Le plus beau château du Japon, UNESCO. 83 bâtiments d'un blanc éclatant. Donjon original de 1609, 6 étages. <strong>1 000¥</strong>, 1h de visite minimum.</p>
          <h3 className="text-xl font-bold mt-6">2. Matsumoto-jo – Le Corbeau Noir</h3><p>Surnommé « le corbeau » pour ses murs noirs. Donjon original, reflet spectaculaire dans les douves. Avec les Alpes japonaises en arrière-plan. <strong>700¥</strong>.</p>
          <h3 className="text-xl font-bold mt-6">3. Osaka-jo</h3><p>Forteresse imposante au cœur d'Osaka, reconstruite en béton (1931) mais musée intéressant et vue panoramique. Parc magnifique pour les cerisiers. <strong>600¥</strong>.</p>
          <h3 className="text-xl font-bold mt-6">4. Kumamoto-jo</h3><p>L'un des trois grands châteaux, en restauration après le séisme de 2016. Les murs de pierre incurvés (musha-gaeshi) sont parmi les plus beaux du Japon.</p>
          <h3 className="text-xl font-bold mt-6">5. Hikone-jo</h3><p>Donjon original compact mais parfaitement préservé. Jardin Genkyu-en adjacent magnifique. Moins touristique que Himeji. <strong>800¥</strong>.</p>
          <h3 className="text-xl font-bold mt-6">6-10. Autres châteaux remarquables</h3>
          <ul><li><strong>6. Inuyama-jo</strong> : le plus ancien donjon du Japon (1537). Vue sur la rivière Kiso. 550¥</li><li><strong>7. Nagoya-jo</strong> : reconstruit avec le palais Honmaru magnifiquement restauré. 500¥</li><li><strong>8. Nijo-jo (Kyoto)</strong> : résidence du shogun Tokugawa. Planchers « rossignol » qui chantent. UNESCO. 800¥</li><li><strong>9. Matsuyama-jo (Shikoku)</strong> : donjon original perché sur une colline, accessible en télésiège. 520¥</li><li><strong>10. Hirosaki-jo (Tohoku)</strong> : petit mais entouré de 2 600 cerisiers. Spectaculaire au printemps. 320¥</li></ul>
          <div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Les châteaux japonais ne sont pas que des monuments historiques : ce sont des <strong>symboles vivants de l'esthétique japonaise</strong>, où la puissance militaire s'exprime avec une élégance sans pareille.</p></div>
          <FAQSection faqs={faqs} className="mt-10" />
          <OrganiserVoyageBlock destination="Japon" showVols showHotel showActivites />
          <div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }, { label: "Temples du Japon", url: "/blog/temples-japon" }, { label: "Villages traditionnels", url: "/blog/villages-traditionnels-japon" }, { label: "Itinéraire Japon 10 jours", url: "/blog/itineraire-japon-10-jours" }].map((link, idx) => (<Link key={idx} to={link.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{link.label}</span></Link>))}</div></div>
          <div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
          <div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div>
        </article>
      </main>
      <Footer />
    </div>
  );
};
export default ChateauxJapon;
