import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Utensils } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const CoutRepasJapon = () => { const faqs = [{ question: "Combien coûte un repas moyen au Japon ?", answer: "Un repas au restaurant coûte 7-15€. Un repas en konbini 3-5€. Un repas gastronomique 30-100€+. La nourriture est l'un des postes les plus abordables au Japon." }]; return (<div className="min-h-screen flex flex-col"><SEO title="Combien Coûte un Repas au Japon : Prix Détaillés" description="Prix détaillés des repas au Japon. Ramen, sushi, konbini, restaurant : combien coûte la nourriture au Japon avec des exemples concrets par type de cuisine." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-12" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Coût Repas Japon", url: "/blog/cout-repas-japon" }]} /><Header /><main className="flex-grow pt-24"><header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Budget</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Combien Coûte un Repas au Japon</h1><p className="text-xl text-white/90">Tous les prix détaillés de la nourriture au Japon</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 12 juil. 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 9 min</span></div></div></div></header>
<article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg"><p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">La nourriture au Japon est un <strong>rapport qualité-prix exceptionnel</strong>. Du konbini au restaurant étoilé Michelin, chaque gamme de prix offre une qualité que peu de pays peuvent égaler.</p>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Utensils className="h-7 w-7 text-ocean" /> Prix par Type de Repas</h2>
<div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 font-bold">Type</th><th className="py-3 px-4 font-bold">Prix moyen</th></tr></thead><tbody>
<tr className="border-b border-border/50"><td className="py-2 px-4">Onigiri (konbini)</td><td className="py-2 px-4">100-180¥ (0,65-1,15€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Bento (konbini)</td><td className="py-2 px-4">400-700¥ (2,60-4,50€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Gyudon (chaîne)</td><td className="py-2 px-4">400-700¥ (2,60-4,50€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Ramen</td><td className="py-2 px-4">700-1200¥ (4,50-7,70€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Sushi (kaiten-zushi)</td><td className="py-2 px-4">1000-2500¥ (6,45-16€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tempura</td><td className="py-2 px-4">800-1500¥ (5,15-9,70€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Okonomiyaki</td><td className="py-2 px-4">800-1500¥ (5,15-9,70€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Izakaya (soirée)</td><td className="py-2 px-4">2000-4000¥ (13-26€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Kaiseki (gastronomique)</td><td className="py-2 px-4">8000-30000¥ (52-194€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Café/thé</td><td className="py-2 px-4">300-600¥ (1,95-3,90€)</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Bière (izakaya)</td><td className="py-2 px-4">400-700¥ (2,60-4,50€)</td></tr>
</tbody></table></div>
<div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Le Japon est le seul pays au monde où un <strong>repas à 5€ peut être mémorable</strong>. Un ramen fumant dans un petit restaurant de quartier, des sushis sur tapis roulant, un bento de konbini : la qualité est constante à chaque prix.</p></div>
<FAQSection faqs={faqs} className="mt-10" /><OrganiserVoyageBlock destination="Japon" showVols showHotel />
<div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Budget voyage Japon", url: "/blog/budget-voyage-japon" }, { label: "Voyage Japon pas cher", url: "/blog/voyage-japon-pas-cher" }, { label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }].map((l, i) => (<Link key={i} to={l.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{l.label}</span></Link>))}</div></div>
<div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
<div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div></article></main><Footer /></div>); };
export default CoutRepasJapon;
