import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Star } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const FestivalsJapon = () => {
  const faqs = [{ question: "Quels sont les plus grands festivals du Japon ?", answer: "Les trois plus grands matsuri sont : Gion Matsuri (Kyoto, juillet), Tenjin Matsuri (Osaka, juillet) et Kanda Matsuri (Tokyo, mai). Chacun attire des millions de visiteurs." }, { question: "Peut-on participer aux festivals ?", answer: "Oui ! La plupart des festivals sont gratuits et ouverts à tous. Certains permettent même aux visiteurs de porter un yukata et de participer aux processions." }];
  return (
    <div className="min-h-screen flex flex-col">
      <SEO title="Les Festivals Japonais à Voir : Matsuri Guide" description="Guide des plus beaux festivals (matsuri) du Japon. Gion Matsuri, feux d'artifice, Nebuta : calendrier, traditions et conseils pour assister aux festivals japonais." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-05" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Festivals Japon", url: "/blog/festivals-japon" }]} />
      <Header />
      <main className="flex-grow pt-24">
        <header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Inspiration</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Les Festivals Japonais à Voir Absolument</h1><p className="text-xl text-white/90">Matsuri, feux d'artifice et traditions : le calendrier des fêtes</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 5 juillet 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 12 min de lecture</span></div></div></div></header>
        <article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg">
          <p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">Les <strong>matsuri</strong> (festivals) font partie de l'ADN culturel du Japon. Chaque mois de l'année, des centaines de festivals célèbrent les saisons, les divinités et les traditions avec des <strong>processions spectaculaires, feux d'artifice géants et performances ancestrales</strong>.</p>
          <h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Star className="h-7 w-7 text-ocean" /> Les Grands Festivals par Saison</h2>
          <h3 className="text-xl font-bold mt-6">🌸 Printemps</h3>
          <ul><li><strong>Hanami</strong> (mars-avril) : fête des cerisiers en fleurs dans tout le Japon</li><li><strong>Kanda Matsuri</strong> (Tokyo, mi-mai) : procession de 200 chars dans le quartier d'Akihabara</li><li><strong>Sanja Matsuri</strong> (Tokyo, mi-mai) : le festival le plus sauvage de Tokyo, 2 millions de visiteurs</li></ul>
          <h3 className="text-xl font-bold mt-6">☀️ Été</h3>
          <ul><li><strong>Gion Matsuri</strong> (Kyoto, juillet) ⭐ : le plus célèbre festival du Japon, chars monumentaux et processions dans Gion. Dure tout le mois de juillet</li><li><strong>Tenjin Matsuri</strong> (Osaka, 24-25 juillet) : procession de bateaux illuminés sur la rivière, feux d'artifice</li><li><strong>Nebuta Matsuri</strong> (Aomori, début août) : chars illuminés géants représentant des guerriers, absolument spectaculaire</li><li><strong>Awa Odori</strong> (Tokushima, mi-août) : la plus grande danse collective du Japon, 1 million de spectateurs</li><li><strong>Feux d'artifice (hanabi)</strong> : juillet-août, les plus grands à Sumida (Tokyo) et Tenjin (Osaka)</li></ul>
          <h3 className="text-xl font-bold mt-6">🍁 Automne</h3>
          <ul><li><strong>Takayama Matsuri</strong> (octobre) : chars en bois ornés de marionnettes mécaniques, UNESCO</li><li><strong>Jidai Matsuri</strong> (Kyoto, 22 octobre) : procession historique retraçant 1 200 ans d'histoire</li></ul>
          <h3 className="text-xl font-bold mt-6">❄️ Hiver</h3>
          <ul><li><strong>Festival de Neige de Sapporo</strong> (février) : sculptures de glace géantes dans le parc Odori</li><li><strong>Illuminations</strong> (décembre) : Kobe Luminarie, Nabana no Sato (13 millions de LED), Tokyo Midtown</li><li><strong>Hatsumode</strong> (1er janvier) : première visite au temple/sanctuaire de l'année</li></ul>
          <div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Assister à un matsuri, c'est <strong>toucher l'âme du Japon</strong>. Le son des tambours taiko, l'odeur des yakitori grillés, les kimonos colorés, l'énergie collective : ces moments créent des souvenirs indélébiles.</p></div>
          <FAQSection faqs={faqs} className="mt-10" />
          <OrganiserVoyageBlock destination="Japon" showVols showHotel showActivites />
          <div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }, { label: "Quand partir au Japon", url: "/blog/quand-partir-japon" }, { label: "Japon en été", url: "/blog/japon-ete" }, { label: "Cerisiers en fleurs", url: "/blog/cerisiers-japon" }].map((link, idx) => (<Link key={idx} to={link.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{link.label}</span></Link>))}</div></div>
          <div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
          <div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div>
        </article>
      </main>
      <Footer />
    </div>
  );
};
export default FestivalsJapon;
