import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const JaponAutomne = () => { const faqs = [{ question: "Quand voir les érables au Japon ?", answer: "Mi-octobre à Hokkaido, fin octobre-début novembre à Tohoku et Alpes, mi-novembre à Tokyo et Kyoto, fin novembre-début décembre au sud." }, { question: "L'automne est-il une bonne période ?", answer: "C'est la meilleure période avec le printemps : températures idéales (15-22°C), ciel bleu, couleurs spectaculaires et moins de foule qu'au printemps." }]; return (<div className="min-h-screen flex flex-col"><SEO title="Japon en Automne : Érables, Temples et Guide" description="Guide du Japon en automne. Érables flamboyants (koyo), meilleurs spots, météo, budget : tout savoir pour voyager au Japon d'octobre à décembre." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-08" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Japon Automne", url: "/blog/japon-automne" }]} /><Header /><main className="flex-grow pt-24"><header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Saisonnier</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Le Japon en Automne : Érables et Splendeurs</h1><p className="text-xl text-white/90">Koyo : quand le Japon s'embrase de rouge et d'or</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 8 juil. 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 11 min</span></div></div></div></header>
<article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg"><p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">L'automne au Japon est un <strong>spectacle naturel à couper le souffle</strong>. Les érables japonais (momiji) transforment les temples, jardins et montagnes en palettes de <strong>rouge, orange et or</strong>. Le koyo (contemplation des feuilles d'automne) est tout aussi important culturellement que le hanami printanier.</p>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">🍁 Calendrier du Koyo</h2><ul><li><strong>Mi-octobre</strong> : Hokkaido (Daisetsuzan)</li><li><strong>Fin octobre</strong> : Tohoku, Nikko, Alpes japonaises</li><li><strong>Mi-novembre</strong> : Tokyo, Kamakura</li><li><strong>Fin novembre</strong> : Kyoto (pic), Nara, Osaka</li><li><strong>Début décembre</strong> : Kyushu, Shikoku</li></ul>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">🍁 Meilleurs Spots</h2><h3 className="text-xl font-bold mt-6">Kyoto ⭐</h3><ul><li><strong>Tofuku-ji</strong> : le plus célèbre spot d'automne, pont surplombant une mer d'érables</li><li><strong>Eikando</strong> : illuminations nocturnes spectaculaires</li><li><strong>Arashiyama</strong> : la forêt de bambous entourée d'érables</li></ul>
<h3 className="text-xl font-bold mt-6">Autres régions</h3><ul><li><strong>Nikko</strong> (Tochigi) : temples UNESCO dans un écrin d'érables</li><li><strong>Hakone</strong> : vue sur le Fuji avec les couleurs d'automne</li><li><strong>Miyajima</strong> : torii flottant + érables</li><li><strong>Koyasan</strong> : cèdres et érables dans un cadre spirituel</li></ul>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">💰 Budget</h2><p>Haute saison à Kyoto (mi-novembre). Prix comparables au printemps pour les hôtels. Ailleurs au Japon, les prix restent raisonnables.</p>
<div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">L'automne japonais est un <strong>émerveillement quotidien</strong>. Chaque jour, les couleurs changent, chaque temple offre un nouveau tableau. C'est la saison où la beauté japonaise atteint son apogée.</p></div>
<FAQSection faqs={faqs} className="mt-10" /><OrganiserVoyageBlock destination="Japon" showVols showHotel showActivites />
<div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Quand partir au Japon", url: "/blog/quand-partir-japon" }, { label: "Que faire à Kyoto", url: "/blog/que-faire-kyoto" }, { label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }].map((l, i) => (<Link key={i} to={l.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{l.label}</span></Link>))}</div></div>
<div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
<div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div></article></main><Footer /></div>); };
export default JaponAutomne;
