import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const JaponEte = () => { const faqs = [{ question: "Fait-il très chaud au Japon en été ?", answer: "Oui, 30-35°C avec une humidité de 80-90%. Tokyo et Osaka sont étouffantes. Hokkaido et les montagnes sont plus agréables (25°C max)." }, { question: "La saison des pluies gâche-t-elle le voyage ?", answer: "La tsuyu (saison des pluies) dure de mi-juin à mi-juillet. Les pluies sont intermittentes, pas continues. Hokkaido n'est pas concerné." }]; return (<div className="min-h-screen flex flex-col"><SEO title="Japon en Été : Festivals, Plages et Conseils" description="Guide du Japon en été. Festivals matsuri, feux d'artifice, plages, Hokkaido : activités, météo et conseils pour voyager au Japon de juin à août." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-07" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Japon Été", url: "/blog/japon-ete" }]} /><Header /><main className="flex-grow pt-24"><header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Saisonnier</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Le Japon en Été : Festivals et Aventures</h1><p className="text-xl text-white/90">Matsuri, feux d'artifice et nature luxuriante</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 7 juil. 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 10 min</span></div></div></div></header>
<article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg"><p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">L'été japonais est <strong>chaud, humide et vibrant d'énergie</strong>. C'est la saison des grands <strong>matsuri</strong> (festivals), des feux d'artifice spectaculaires et de la nature luxuriante. Malgré la chaleur, l'été offre des expériences uniques qu'aucune autre saison ne peut égaler.</p>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">☀️ Météo et Saison des Pluies</h2><p><strong>Tsuyu</strong> (mi-juin à mi-juillet) : pluies intermittentes sur Honshu, Shikoku et Kyushu. Hokkaido est épargné. Juillet-août : 30-35°C, humidité 80-90%.</p><ul><li><strong>Conseil</strong> : emportez un éventail (sensu), une serviette et restez hydraté</li><li><strong>Refuges</strong> : Hokkaido (25°C max), Alpes japonaises, Nikko</li></ul>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">🎆 Festivals d'Été</h2><ul><li><strong>Gion Matsuri</strong> (Kyoto, tout juillet) : le plus célèbre matsuri du Japon</li><li><strong>Tenjin Matsuri</strong> (Osaka, 24-25 juillet) : bateaux illuminés et feux d'artifice</li><li><strong>Nebuta Matsuri</strong> (Aomori, 2-7 août) : chars géants illuminés</li><li><strong>Hanabi</strong> (feux d'artifice) : Sumida (Tokyo), Nagaoka, Omagari — spectacles de 10 000+ fusées</li><li><strong>Obon</strong> (mi-août) : fête des ancêtres, lanternes flottantes, danse Bon Odori</li></ul>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">🏖️ Activités d'Été</h2><ul><li><strong>Ascension du Mont Fuji</strong> (juillet-août uniquement)</li><li><strong>Plages d'Okinawa</strong> : eaux turquoise et récifs coralliens</li><li><strong>Lavande de Furano</strong> (Hokkaido, juillet)</li><li><strong>Randonnée dans les Alpes japonaises</strong> (Kamikochi)</li><li><strong>Kakigori</strong> : glace pilée aux sirops, dessert estival incontournable</li></ul>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10">💰 Budget</h2><p>Saison intermédiaire (sauf Obon mi-août). Vols A/R : 500-800€. Hébergement prix normal sauf Obon (+20-30%).</p>
<div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">L'été japonais est une <strong>explosion sensorielle</strong> : le son des cigales (semi), l'odeur des yakitori grillés aux festivals, la fraîcheur d'un kakigori sous le soleil brûlant. C'est le Japon à son plus vivant.</p></div>
<FAQSection faqs={faqs} className="mt-10" /><OrganiserVoyageBlock destination="Japon" showVols showHotel showActivites />
<div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Quand partir au Japon", url: "/blog/quand-partir-japon" }, { label: "Festivals japonais", url: "/blog/festivals-japon" }, { label: "Guide complet du Japon", url: "/blog/guide-complet-japon" }].map((l, i) => (<Link key={i} to={l.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{l.label}</span></Link>))}</div></div>
<div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
<div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div></article></main><Footer /></div>); };
export default JaponEte;
