import React from "react";import Header from "@/components/Header";import Footer from "@/components/Footer";import SEO from "@/components/SEO";import FAQSection from "@/components/FAQSection";import { OrganiserVoyageBlock } from "@/components/affiliate";import { Link } from "react-router-dom";import { Button } from "@/components/ui/button";import { Calendar, MapPin, Clock, Compass, Home } from "lucide-react";import japonImage from "@/assets/destinations/japon.jpg";
const PrixHotelsJapon = () => { const faqs = [{ question: "Combien coûte un hôtel au Japon ?", answer: "Un capsule hotel coûte 25-45€, un business hotel 50-100€, un ryokan 80-300€ et un hôtel de luxe 200-800€. Les prix varient selon la ville et la saison." }]; return (<div className="min-h-screen flex flex-col"><SEO title="Prix des Hôtels au Japon : Tarifs par Ville" description="Prix détaillés des hôtels au Japon par ville et catégorie. Capsule, business hotel, ryokan, luxe : comparatif des tarifs à Tokyo, Kyoto, Osaka et plus." image={japonImage} ogType="article" hideH1 articleMeta={{ author: "Cap sur le Monde", datePublished: "2025-07-13" }} breadcrumbs={[{ name: "Accueil", url: "/" }, { name: "Blog", url: "/blog" }, { name: "Prix Hôtels Japon", url: "/blog/prix-hotels-japon" }]} /><Header /><main className="flex-grow pt-24"><header className="relative h-[60vh] md:h-[70vh] bg-cover bg-center" style={{ backgroundImage: `url(${japonImage})` }}><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/70" /><div className="relative container mx-auto px-4 h-full flex items-end pb-16 z-10"><div className="text-white max-w-4xl"><span className="inline-block bg-ocean/80 text-white text-sm font-medium px-3 py-1 rounded mb-4">Budget</span><h1 className="text-4xl md:text-6xl font-elegant font-extrabold mb-4 drop-shadow-lg">Prix des Hôtels au Japon par Ville</h1><p className="text-xl text-white/90">Comparatif détaillé des tarifs d'hébergement</p><div className="flex items-center gap-6 mt-6 pt-4 border-t border-white/30 text-sm text-white/90"><span className="flex items-center gap-2"><Calendar className="h-4 w-4" /> 13 juil. 2025</span><span className="flex items-center gap-2"><Clock className="h-4 w-4" /> 9 min</span></div></div></div></header>
<article className="container mx-auto px-4 py-12 max-w-4xl prose prose-lg"><p className="text-lg leading-relaxed text-muted-foreground first-letter:text-5xl first-letter:font-bold first-letter:text-ocean first-letter:mr-2 first-letter:float-left">L'hébergement est souvent le <strong>poste le plus important du budget</strong> au Japon. Ce guide détaille les <strong>prix réels</strong> par ville et par catégorie pour vous aider à planifier précisément.</p>
<h2 className="text-3xl font-elegant font-bold text-primary mt-10 flex items-center gap-3"><Home className="h-7 w-7 text-ocean" /> Tarifs par Ville et Catégorie</h2>
<div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-border"><th className="py-3 px-4 font-bold">Ville</th><th className="py-3 px-4 font-bold">Auberge</th><th className="py-3 px-4 font-bold">Capsule</th><th className="py-3 px-4 font-bold">Business</th><th className="py-3 px-4 font-bold">Confort</th><th className="py-3 px-4 font-bold">Luxe</th></tr></thead><tbody>
<tr className="border-b border-border/50"><td className="py-2 px-4">Tokyo</td><td className="py-2 px-4">20-30€</td><td className="py-2 px-4">30-50€</td><td className="py-2 px-4">60-120€</td><td className="py-2 px-4">120-250€</td><td className="py-2 px-4">250-800€</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Kyoto</td><td className="py-2 px-4">18-28€</td><td className="py-2 px-4">25-45€</td><td className="py-2 px-4">50-100€</td><td className="py-2 px-4">100-200€</td><td className="py-2 px-4">200-600€</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Osaka</td><td className="py-2 px-4">15-25€</td><td className="py-2 px-4">25-40€</td><td className="py-2 px-4">45-90€</td><td className="py-2 px-4">90-180€</td><td className="py-2 px-4">180-500€</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Hiroshima</td><td className="py-2 px-4">15-22€</td><td className="py-2 px-4">22-35€</td><td className="py-2 px-4">40-80€</td><td className="py-2 px-4">80-150€</td><td className="py-2 px-4">150-350€</td></tr>
<tr className="border-b border-border/50"><td className="py-2 px-4">Sapporo</td><td className="py-2 px-4">15-22€</td><td className="py-2 px-4">22-35€</td><td className="py-2 px-4">40-80€</td><td className="py-2 px-4">80-150€</td><td className="py-2 px-4">150-400€</td></tr>
</tbody></table></div>
<p className="text-sm text-muted-foreground mt-2">* Prix en basse/moyenne saison. En haute saison (cerisiers, automne, Golden Week), ajoutez +30-50%.</p>
<div className="mt-10 p-6 bg-accent/30 rounded-lg border-l-4 border-ocean"><p className="text-lg text-foreground italic leading-relaxed">Conseil : <strong>mélangez les types d'hébergement</strong> pour optimiser votre budget. Business hotel en ville, ryokan pour une nuit spéciale, capsule pour l'expérience.</p></div>
<FAQSection faqs={faqs} className="mt-10" /><OrganiserVoyageBlock destination="Japon" showHotel showVols />
<div className="mt-10 p-6 bg-muted/30 rounded-lg border border-border"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><Compass className="h-5 w-5 text-ocean" /> À lire aussi</h3><div className="grid gap-2 sm:grid-cols-2">{[{ label: "Où dormir au Japon", url: "/blog/ou-dormir-japon" }, { label: "Budget voyage Japon", url: "/blog/budget-voyage-japon" }, { label: "Meilleurs hôtels Tokyo", url: "/blog/meilleurs-hotels-tokyo" }, { label: "Meilleurs hôtels Kyoto", url: "/blog/meilleurs-hotels-kyoto" }].map((l, i) => (<Link key={i} to={l.url} onClick={() => window.scrollTo(0, 0)} className="flex items-center gap-2 p-2 rounded-md hover:bg-background transition-all text-muted-foreground hover:text-ocean text-sm"><span className="text-ocean">→</span><span>{l.label}</span></Link>))}</div></div>
<div className="mt-10 p-6 bg-ocean/5 rounded-lg border border-ocean/20"><h3 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2"><MapPin className="h-5 w-5 text-ocean" /> 🗺️ Destinations</h3><div className="flex flex-wrap gap-2">{[{ label: "🇯🇵 Japon", url: "/destinations/japon" }].map((d, i) => (<Link key={i} to={d.url} onClick={() => window.scrollTo(0, 0)} className="inline-flex items-center gap-1 px-3 py-1.5 bg-background border border-border rounded-full text-sm hover:border-ocean hover:text-ocean transition-colors">{d.label}</Link>))}</div></div>
<div className="mt-10 flex flex-col sm:flex-row gap-4"><Button asChild className="flex-1 bg-ocean hover:bg-ocean/90"><Link to="/destinations/japon" onClick={() => window.scrollTo(0, 0)}>Découvrir le Japon</Link></Button><Button asChild variant="outline" className="flex-1"><Link to="/blog" onClick={() => window.scrollTo(0, 0)}>Retour au blog</Link></Button></div></article></main><Footer /></div>); };
export default PrixHotelsJapon;
